# Cloud Build configuration for ADK Frontend
# This builds the Next.js frontend and deploys it to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'nextjs/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/adk-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/adk-frontend:latest',
      'nextjs'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/adk-frontend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/adk-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'adk-frontend',
      '--image', 'gcr.io/$PROJECT_ID/adk-frontend:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '900s',
      '--set-env-vars',
      'CLOUD_RUN_SERVICE_URL=https://adk-backend-aug23-310799546989.us-central1.run.app,ADK_APP_NAME=upskilling_agent,NODE_ENV=production'
    ]

# Store the image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/adk-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/adk-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
