name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Authenticate with service account
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # 3. Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          install_components: gke-gcloud-auth-plugin

      # 4. Build and push Docker image
      - name: Build Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/adk-backend:latest"
          gcloud builds submit app/ --tag $IMAGE

      # 5. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/adk-backend:latest"
          gcloud run deploy adk-backend \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
