name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Authenticate with service account
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # 3. Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          install_components: gke-gcloud-auth-plugin

      # 4. Build and push Docker image
      - name: Build Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/adk-backend-git:latest"
          gcloud builds submit app/ --tag $IMAGE

      # 5. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/adk-backend-git:latest"
          gcloud run deploy adk-backend-git \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "APP_NAME=${{ secrets.APP_NAME }},DB_NAME=${{ secrets.DB_NAME }},DD_API_KEY=${{ secrets.DD_API_KEY }},DD_SITE=${{ secrets.DD_SITE }},DD_TRACE_ENABLED=${{ secrets.DD_TRACE_ENABLED }},GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }},GOOGLE_CLOUD_LOCATION=${{ secrets.GOOGLE_CLOUD_LOCATION }},GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }},GOOGLE_CLOUD_STAGING_BUCKET=${{ secrets.GOOGLE_CLOUD_STAGING_BUCKET }},GOOGLE_GENAI_USE_VERTEXAI=${{ secrets.GOOGLE_GENAI_USE_VERTEXAI }}"
